version: "3.8"

networks:
  db-net:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    command: postgres
    env_file:
      .env
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    expose:
      - $POSTGRES_PORT
    volumes:
      - ./docker/dbdata:/var/lib/POSTGRES/
    networks:
      - db-net

  template-nest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./docker/app/logs:/app/logs
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - db-net
    depends_on:
      - db